version: '2'
services:
  db:
    image: postgres:9.5
  nginx:
    build: ./nginx
    command: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/log:/var/log/nginx
    volumes_from:
      - jarjs:ro
    links:
      - user_service
    depends_on:
      - user_service
      - jarjs
  user_service:
    build: ./user_service
    command: rails server --binding 0.0.0.0 --port 3000
    volumes:
      - ./user_service:/usr/src/app
    ports:
      - 3000:3000
    links:
      - db
    depends_on:
      - db
  jarjs:
    build: ./jarjs
    command: /bin/true
    volumes:
      - ./jarjs:/usr/src/app
