version: '2'
services:
  # user_service_db:
  #   extends:
  #     file: ./user_service/docker-compose.yml
  #     service: db
  # user_service:
  #   extends:
  #     file: ./user_service/docker-compose.yml
  #     service: user_service
  #   links:
  #     - user_service_db:db
  #   depends_on:
  #     - user_service_db
  web_server:
    tty: true
    build: ./nginx
    command: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/log:/var/log/nginx
    volumes_from:
      - jarjs:ro
    # links:
      # - user_service
    depends_on:
      - jarjs
      # - user_service
  jarjs:
    build: ./jarjs
    command: /bin/true
