version: '2'
services:
  db:
    image: postgres:9.5
  user_service:
    build: ./user_service
    command: rails server --binding 0.0.0.0 --port 3000
    volumes:
      - ./user_service:/usr/src/app
    ports:
      - 3000:3000
    links:
      - db
    depends_on:
      - db
